# This workflow will do a clean install of node dependencies, build the source
# code and run tests in block on the latest version of node.

name: Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Runs all tests for SRE
    steps:
      - uses: actions/checkout@v2
      - name: Setup Speech Rule Engine
        run: npm ci
      - name: Set up tests
        run: |
          sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init --recursive
          cd sre-tests; ln -s .. speech-rule-engine; npm ci; sudo chmod -R 777 .;
      - name: Run tests
        run: npm run actionTest js/actions/
