# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: 
          - node-version: 15.x

    steps:
    - uses: actions/checkout@v2
    - name: Changes cloning method
      run: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup test module
      run: cd sre-tests; sudo chmod -R 777 .; npm ci; npm run prepare
    - name: Setup Speech Rule Engine
      run: npm ci; npm run build --if-present
    - name: SRE Tests
      run: npm run actionTest
